#+ summary: Count of Anatomical Structures
#+ description: Count of Anatomical Structures that occur in the 3D Reference Organs

PREFIX ccf: <http://purl.org/ccf/>
PREFIX CCF: <https://purl.humanatlas.io/graph/ccf>

SELECT (COUNT(DISTINCT(?as_id)) as ?as_cnt)
FROM CCF:
WHERE {
  ?as3d a ccf:spatial_entity ;
    ccf:has_reference_organ ?ref_organ ;
    ccf:representation_of ?as_id .
}
