# Count the unique number of Samples 

PREFIX ccf: <http://purl.org/ccf/>

SELECT (COUNT(DISTINCT ?sample) as ?sample_ct)
FROM <https://purl.humanatlas.io/graph/hra-pop>
FROM <https://purl.humanatlas.io/ds-graph/hra-pop-full>
WHERE {
  ?sample a ccf:Sample
}
