#+ summary: Count of Cells and unique Cell Types
#+ description: Count of Cells and unique Cell Types that occur in the Enriched RUI Locations

PREFIX ctpop: <https://cns-iu.github.io/hra-cell-type-populations-supporting-information/data/enriched_rui_locations.jsonld#>
PREFIX ccf: <http://purl.org/ccf/>

SELECT
  (COUNT(DISTINCT(?cell_id)) as ?unique_cell_type_count)
  (SUM(?cell_count) as ?cell_count)
FROM ctpop:graph
WHERE {
  [] a ccf:Dataset ;
    ccf:has_cell_summary [
      ccf:has_cell_summary_row [
        ccf:cell_id ?cell_id ;
        ccf:cell_count ?cell_count ;
      ] ;
    ] .
}
