# Query the information of Samples

PREFIX ccf: <http://purl.org/ccf/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?sample ?s_sample_type ?s_label ?s_description ?s_link ?rui_location_url ?x_dimension ?y_dimension ?z_dimension ?creator ?creator_first_name ?creator_last_name ?as_id (count(DISTINCT ?cell_id) as ?ct_cnt)
FROM <https://purl.humanatlas.io/graph/hra-pop>
FROM <https://purl.humanatlas.io/ds-graph/hra-pop-full>
WHERE {
  ?sample a ccf:Sample.
  ?sample ccf:sample_type ?s_sample_type.
  ?sample rdfs:label ?s_label.
  ?sample rdfs:comment ?s_description.
  ?sample ccf:url ?s_link.
  ?sample ccf:has_registration_location ?rui_location_url.
  ?rui_location_url ccf:x_dimension ?x_dimension.
  ?rui_location_url ccf:y_dimension ?y_dimension.
  ?rui_location_url ccf:z_dimension ?z_dimension.
  ?rui_location_url dcterms:creator ?creator.
  ?rui_location_url ccf:creator_first_name ?creator_first_name.
  ?rui_location_url ccf:creator_last_name ?creator_last_name.
  


  OPTIONAL {
      ?rui_location_url ccf:has_collision_summary ?collision_summary.
      ?collisionsummary ccf:has_collision_item ?collision.
      ?collision ccf:reference_organ ?reference_organ.
      ?collision ccf:as_3d_id ?as_3d_id.
      ?collision ccf:as_id ?as_id.
      ?collision ccf:as_label ?as_label.

      ?rui_location_url ccf:has_cell_summary ?cell_summary .
      ?cell_summary ccf:has_cell_summary_row ?cell_summary_row .
      ?cell_summary_row ccf:cell_id ?cell_id .
    }
}
GROUP BY ?sample ?s_sample_type ?s_label ?s_description ?s_link ?rui_location_url ?x_dimension ?y_dimension ?z_dimension ?creator ?creator_first_name ?creator_last_name ?as_id