# Query Samples and associated description

PREFIX ccf: <http://purl.org/ccf/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(DISTINCT ?sample) AS ?sample_ct) (COUNT(DISTINCT ?description) AS ?description_ct)
FROM <https://purl.humanatlas.io/graph/hra-pop>
FROM <https://purl.humanatlas.io/ds-graph/hra-pop-full>
WHERE {
  ?sample a ccf:Sample .
  ?sample rdfs:comment ?description .
}