# Count the unique number of datasets by modality
PREFIX ccf: <http://purl.org/ccf/>

SELECT (COUNT(DISTINCT ?dataset) AS ?dataset_ct) ?modality 
FROM <https://purl.humanatlas.io/graph/hra-pop>

WHERE {
    ?dataset a ccf:Dataset;
  ccf:has_cell_summary 
      [
  		ccf:modality ?modality
    ]
    
}

GROUP BY ?modality