# Query the list of Spatial Placements in hra-pop

PREFIX ccf: <http://purl.org/ccf/>

SELECT DISTINCT ?spatial_placement
FROM <https://purl.humanatlas.io/graph/hra-pop>
FROM <https://purl.humanatlas.io/ds-graph/hra-pop-full>
WHERE {
    ?spatial_placement a ccf:SpatialPlacement.
}

